# Funding sources for NoOutcomes ABA.
# See: https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

ko_fi: nooutcomeaba
buy_me_a_coffee: no.outcome.aba
# github: # GitHub Sponsors: pending - add username once enabled
custom:
  - https://paypal.me/kablubfowles
