# Support No Outcome
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

ko_fi: nooutcomeaba
buy_me_a_coffee: no.outcome.aba
custom: ['https://venmo.com/u/kablubfowles']

# github: [your-username]   # uncomment once GitHub Sponsors approval is granted
