/* BUILDS THE CONSOLE BENCH, one paste-ready file per tool:
 * scripts/bench/console/<tool>.js, from cases/<tool>.json, lib/checks.mjs (with
 * the parent checker it imports) and lib/page-bench.mjs.
 *
 *   node scripts/bench/build-console.mjs           write every tool's file
 *   node scripts/bench/build-console.mjs --check   write nothing; exit 1 if stale
 *
 * Edit the cases, the checks or the runner, never a generated file. */
import { readFileSync, writeFileSync, readdirSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const BENCH = path.join(ROOT, 'scripts/bench');
export const OUT_DIR = path.join(BENCH, 'console');

/* A module as page code: the same source, minus its imports and export words. */
function asPageCode(rel) {
  return readFileSync(path.join(ROOT, rel), 'utf8')
    .split('\n').filter((l) => !/^import\s/.test(l)).join('\n')
    .replace(/^export (async function|function|const)/gm, '$1')
    .trim();
}

const indent = (s) => s.replace(/\n/g, '\n  ');

export function tools() {
  return readdirSync(path.join(BENCH, 'cases')).filter((f) => f.endsWith('.json')).map((f) => f.replace(/\.json$/, '')).sort();
}

export function render(tool) {
  const set = JSON.parse(readFileSync(path.join(BENCH, 'cases', `${tool}.json`), 'utf8'));
  const cases = set.cases;
  const page = cases[0].page;
  return `/* NOTE BENCH, ${tool.toUpperCase()}, FOR THE CONSOLE. Generated by
 * scripts/bench/build-console.mjs; edit the cases, the checks or the runner,
 * never this file.
 *
 * Open tools.nooutco.me${page} logged in, keep the tab in front, and paste
 * the whole file into the console. It runs the ${cases.length} invented cases in
 * scripts/bench/cases/${tool}.json the way a user does: types each one, presses
 * Generate, answers the page's questions from the case's hidden details,
 * Sends, reads the note back and scores it. Between cases it presses Clear.
 *
 * It costs ${cases.length} drafts plus their question rounds, and sends only the
 * invented cases below. The results land on your clipboard. */
(() => {
  /* Chrome lends the console's copy() only while pasted code first runs, so
     it is taken before the first await. The report also stays on window. */
  const copyNow = typeof copy === 'function' ? copy : null;
  const CASES = ${indent(JSON.stringify(cases, null, 2))};

  // Each module keeps its own scope, as it has on disk.
  const checkParentDraft = (() => {
    ${indent(indent(asPageCode('scripts/lib/parent-shape-checks.mjs')))}
    return checkParentDraft;
  })();

  const checkNote = (() => {
    ${indent(indent(asPageCode('scripts/bench/lib/checks.mjs')))}
    return checkNote;
  })();

  ${indent(asPageCode('scripts/bench/lib/page-bench.mjs'))}

  if (location.pathname !== ${JSON.stringify(page)}) {
    throw new Error('Open ' + ${JSON.stringify(page)} + ' on tools.nooutco.me first, then paste this again.');
  }
  return benchInPage(CASES, checkNote).then((report) => {
    console.table(report.results.map((r) => ({ case: r.id, pass: !r.fails.length, typed: r.typed ? r.typed.total : '-', seconds: r.seconds || '-', fails: r.fails.join(' | ') || '-' })));
    window.benchReport = report;
    try {
      if (!copyNow) throw new Error('no console copy()');
      copyNow(JSON.stringify(report, null, 2));
      console.log('The results and the notes are on your clipboard.');
    } catch (e) {
      console.log('To put the results on your clipboard, type copy(benchReport) and press Enter.');
    }
    return report;
  });
})();
`;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const check = process.argv.includes('--check');
  let stale = 0;
  if (!check) mkdirSync(OUT_DIR, { recursive: true });
  for (const tool of tools()) {
    const file = path.join(OUT_DIR, `${tool}.js`);
    const rel = path.relative(process.cwd(), file);
    if (check) {
      let current = false;
      try { current = readFileSync(file, 'utf8') === render(tool); } catch { current = false; }
      if (!current) stale += 1;
      console.log(current ? `${rel} is current` : `${rel} is stale: run node scripts/bench/build-console.mjs`);
    } else {
      writeFileSync(file, render(tool));
      console.log(`wrote ${rel}`);
    }
  }
  process.exit(stale ? 1 : 0);
}
