/* ── Think or Say? — Level 1 "Clear" ───────────────────────────────────
   Early acquisition. The answer is obvious to anyone holding the rule: the
   discrimination is available from the utterance itself and no card asks the
   learner to weigh two criterial dimensions against each other.

   THINK side is blatant — angry words, openly rude statements, private things
   said out loud. SAY side is equally blatant — thanking, asking for help,
   telling a grown-up you feel sick, speaking up about danger, a genuine
   compliment.

   CONTENT RULE (all three levels): only mild, non-name-calling utterances are
   QUOTED. Anything harsher is described, never printed. No slurs, no profanity,
   no specific insults — the game must not teach the vocabulary it warns against.

   ORDER IS DATA. The array order is the deck order under `order: sequential`,
   and it is arranged so the answers do not run in step with the tile
   counterbalance (which alternates on the trial index). Blocks of four run
   THINK, SAY, SAY, THINK; the tail runs SAY. Reordering this array can create a
   perfect position cue — think-or-say-levels.spec.js measures it.
   ----------------------------------------------------------------------- */
(function (global) {
  'use strict';

  global.ThinkOrSayLevel1 = {
    id: 1,
    name: 'Clear',
    blurb: 'Early acquisition - the answer is obvious once you hold the rule.',
    cards: [
      // ── block 1 ──
      { id: 'L1-01', level: 1, cat: 'work', answer: 'think',
        situation: 'Your friend shows you a drawing they made. You do not like how it looks.',
        utterance: 'That drawing looks bad.', sayVerb: 'say', object: 'these words',
        features: { selfEsteem: 'hurts', relationship: 'close-friend' },
        vary: { setting: 'school', person: 'peer', topic: 'work', form: 'statement' },
        reason: 'Think it. They worked hard on it - these words would hurt their feelings.' },
      { id: 'L1-02', level: 1, cat: 'kind', answer: 'say',
        situation: 'Your friend shows you a drawing they made. You really like how it looks.',
        utterance: 'That drawing looks great!', sayVerb: 'say', object: 'these words',
        features: { selfEsteem: 'lifts', relationship: 'close-friend' },
        vary: { setting: 'school', person: 'peer', topic: 'work', form: 'exclamation' },
        reason: 'Say it! A kind, true compliment makes your friend feel proud.' },
      { id: 'L1-04', level: 1, cat: 'kind', answer: 'say',
        situation: 'A classmate tells you they just learned to tie their own shoes.',
        utterance: 'You can tie your shoes!', sayVerb: 'say', object: 'these words',
        features: { privacy: 'not-private', relationship: 'classmate' },
        vary: { setting: 'school', person: 'peer', topic: 'body', form: 'exclamation' },
        reason: 'Say it! This is happy news they wanted to share, so saying it is kind.' },
      { id: 'L1-03', level: 1, cat: 'private', answer: 'think',
        situation: 'A classmate tells you quietly that they still wet the bed sometimes.',
        utterance: 'You wet the bed.', sayVerb: 'say', object: 'these words',
        features: { privacy: 'private', relationship: 'classmate' },
        vary: { setting: 'school', person: 'peer', topic: 'body', form: 'statement' },
        reason: 'Think it. They told you something private - saying it out loud would embarrass them.' },

      // ── block 2 ──
      { id: 'L1-06', level: 1, cat: 'looks', answer: 'think',
        situation: 'You are right beside your friend at the coat hooks. Nobody else is near. Their coat is much too small for them now.',
        utterance: 'Your coat is too small.', sayVerb: 'say', object: 'these words',
        features: { changeability: 'not-fixable', audience: 'just-them' },
        vary: { setting: 'school', person: 'peer', topic: 'belongings', form: 'statement' },
        reason: 'Think it. They cannot change their coat right now, so saying it would only make them feel bad.' },
      { id: 'L1-05', level: 1, cat: 'other', answer: 'say',
        situation: 'You are right beside your friend at the coat hooks. Nobody else is near. Their coat is inside out.',
        utterance: 'Your coat is inside out.', sayVerb: 'say', object: 'these words',
        features: { changeability: 'fixable-now', audience: 'just-them' },
        vary: { setting: 'school', person: 'peer', topic: 'belongings', form: 'statement' },
        reason: 'Say it - quietly, just to them. They can fix it right now, so telling them helps.' },
      { id: 'L1-07', level: 1, cat: 'other', answer: 'say',
        situation: 'You are sitting right next to your friend. Nobody else can hear you. Their shoelace is undone.',
        utterance: 'Your shoelace is undone.', sayVerb: 'say', object: 'these words',
        features: { audience: 'just-them', changeability: 'fixable-now' },
        vary: { setting: 'school', person: 'peer', topic: 'belongings', form: 'statement' },
        reason: 'Say it - quietly, just to them. They can tie it right now.' },
      { id: 'L1-08', level: 1, cat: 'other', answer: 'think',
        situation: 'You are all the way across the noisy gym from your friend. Everyone is in between. Their shoelace is undone.',
        utterance: 'Your shoelace is undone!', sayVerb: 'say', object: 'these words',
        features: { audience: 'others-hear', changeability: 'fixable-now' },
        vary: { setting: 'school', person: 'peer', topic: 'belongings', form: 'exclamation' },
        reason: 'Think it. Shouting it means everyone hears, and that would embarrass your friend. Wait until you are close.' },

      // ── block 3 ──
      { id: 'L1-10', level: 1, cat: 'private', answer: 'think',
        situation: 'Your tummy has hurt all morning. A person you have never met is sitting beside you on the bus.',
        utterance: 'My tummy does not feel good.', sayVerb: 'say', object: 'these words',
        features: { relationship: 'stranger', privacy: 'private' },
        vary: { setting: 'bus', person: 'stranger', topic: 'body', form: 'statement' },
        reason: 'Think it. You do not know this person. Tell your own grown-up instead.' },
      { id: 'L1-09', level: 1, cat: 'other', answer: 'say',
        situation: 'Your tummy has hurt all morning. Your teacher is right beside you.',
        utterance: 'My tummy does not feel good.', sayVerb: 'say', object: 'these words',
        features: { relationship: 'grown-up', privacy: 'private' },
        vary: { setting: 'school', person: 'teacher', topic: 'body', form: 'statement' },
        reason: 'Say it! Telling a grown-up when you feel sick is important.' },
      { id: 'L1-11', level: 1, cat: 'kind', answer: 'say',
        situation: 'Your teacher has finished talking and is looking right at you. You want to show her your drawing.',
        utterance: 'Look at my drawing!', sayVerb: 'say', object: 'these words',
        features: { timing: 'right-moment', relationship: 'grown-up' },
        vary: { setting: 'school', person: 'teacher', topic: 'work', form: 'exclamation' },
        reason: 'Say it! She is free now, so this is a good moment to share.' },
      { id: 'L1-12', level: 1, cat: 'other', answer: 'think',
        situation: 'Your teacher is in the middle of talking to another grown-up. You want to show her your drawing.',
        utterance: 'Look at my drawing!', sayVerb: 'say', object: 'these words',
        features: { timing: 'wrong-moment', relationship: 'grown-up' },
        vary: { setting: 'school', person: 'teacher', topic: 'work', form: 'exclamation' },
        reason: 'Think it for now. She is busy with someone else - you can say it when she is finished.' },

      // ── block 4 ──
      { id: 'L1-14', level: 1, cat: 'other', answer: 'think',
        situation: 'You are across the playground from a classmate. Their shoes are covered in mud.',
        utterance: 'Your shoes are muddy!', sayVerb: 'say', object: 'these words',
        features: { override: 'none', audience: 'others-hear' },
        vary: { setting: 'playground', person: 'peer', topic: 'belongings', form: 'exclamation' },
        reason: 'Think it. Nobody is in danger, and shouting it would embarrass them.' },
      { id: 'L1-13', level: 1, cat: 'other', answer: 'say',
        situation: 'You are across the playground from a classmate. They are about to run into the street where cars are driving.',
        utterance: 'Stop! Cars are coming!', sayVerb: 'tell', object: 'this news',
        features: { override: 'help-or-safety', audience: 'others-hear' },
        vary: { setting: 'playground', person: 'peer', topic: 'body', form: 'exclamation' },
        reason: 'Say it - loudly, and tell a grown-up! When someone might get hurt, it is always right to speak up.' },
      { id: 'L1-16', level: 1, cat: 'kind', answer: 'say',
        situation: 'You count the stickers on the chart. It is true that your classmate filled a whole row today.',
        utterance: 'You filled a whole row!', sayVerb: 'say', object: 'these words',
        features: { truthNotTest: 'true', selfEsteem: 'lifts' },
        vary: { setting: 'school', person: 'peer', topic: 'work', form: 'exclamation' },
        reason: 'Say it! It is true AND it is kind, so it is a good thing to share.' },
      { id: 'L1-15', level: 1, cat: 'work', answer: 'think',
        situation: 'You count the stickers on the chart. It is true that your classmate has the fewest.',
        utterance: 'You have the fewest stickers.', sayVerb: 'say', object: 'these words',
        features: { truthNotTest: 'true', selfEsteem: 'hurts' },
        vary: { setting: 'school', person: 'peer', topic: 'work', form: 'statement' },
        reason: 'Think it. It is true - but true is not the test. It would still hurt.' },

      // ── block 5 ──
      { id: 'L1-17', level: 1, cat: 'other', answer: 'think',
        situation: 'Your whole class is singing a song together. You want to tell your friend about your new shoes.',
        utterance: 'I got new shoes!', sayVerb: 'tell', object: 'this news',
        features: { timing: 'wrong-moment', relationship: 'close-friend' },
        vary: { setting: 'school', person: 'peer', topic: 'belongings', form: 'exclamation' },
        reason: 'Think it for now. Everyone is singing - you can tell your friend at snack time.' },
      { id: 'L1-18', level: 1, cat: 'kind', answer: 'say',
        situation: 'You do not understand how to do the worksheet.',
        utterance: 'Can you help me?', sayVerb: 'ask', object: 'this question',
        features: { override: 'help-or-safety', relationship: 'grown-up' },
        vary: { setting: 'school', person: 'teacher', topic: 'work', form: 'question' },
        reason: 'Say it! Asking for help is always okay.' },
      { id: 'L1-19', level: 1, cat: 'other', answer: 'say',
        situation: 'A classmate has fallen over on the playground and is crying.',
        utterance: 'Someone is hurt!', sayVerb: 'tell', object: 'this news',
        features: { override: 'help-or-safety', audience: 'others-hear' },
        vary: { setting: 'playground', person: 'peer', topic: 'body', form: 'exclamation' },
        reason: 'Say it! When someone is hurt, tell a grown-up straight away.' },
      { id: 'L1-20', level: 1, cat: 'work', answer: 'think',
        situation: 'A classmate gives the wrong answer in class. It is true that the answer was wrong.',
        utterance: 'That was wrong.', sayVerb: 'say', object: 'these words',
        features: { truthNotTest: 'true', selfEsteem: 'hurts' },
        vary: { setting: 'school', person: 'peer', topic: 'work', form: 'statement' },
        reason: 'Think it. It is true, and it would still embarrass them in front of everyone.' },

      // ── block 6 ──
      { id: 'L1-21', level: 1, cat: 'private', answer: 'think',
        situation: 'A kid at school has a small accident and their pants get wet. Other kids are all around.',
        utterance: 'Your pants are wet.', sayVerb: 'say', object: 'these words',
        features: { privacy: 'private', audience: 'others-hear' },
        vary: { setting: 'school', person: 'peer', topic: 'body', form: 'statement' },
        reason: 'Think it. That is private, and saying it with everyone around would feel very embarrassing.' },
      { id: 'L1-22', level: 1, cat: 'kind', answer: 'say',
        situation: 'Your friend gets a new shirt with a dinosaur on it. You love dinosaurs too.',
        utterance: 'I love that shirt!', sayVerb: 'say', object: 'these words',
        features: { selfEsteem: 'lifts', relationship: 'close-friend' },
        vary: { setting: 'school', person: 'peer', topic: 'belongings', form: 'exclamation' },
        reason: 'Say it! A kind compliment will make your friend happy.' },
      { id: 'L1-23', level: 1, cat: 'kind', answer: 'say',
        situation: 'Your classmate shares their snack with you.',
        utterance: 'That was so kind!', sayVerb: 'say', object: 'these words',
        features: { selfEsteem: 'lifts', relationship: 'classmate' },
        vary: { setting: 'school', person: 'peer', topic: 'belongings', form: 'exclamation' },
        reason: 'Say it! Saying thank you makes friends feel good.' },
      { id: 'L1-24', level: 1, cat: 'other', answer: 'think',
        situation: 'Your little brother knocks over the blocks you were building. You feel angry with him.',
        utterance: 'Go away!', sayVerb: 'say', object: 'these words',
        features: { selfEsteem: 'hurts', audience: 'others-hear' },
        vary: { setting: 'home', person: 'sibling', topic: 'belongings', form: 'exclamation' },
        reason: 'Think it. Angry words hurt. You can ask a grown-up for help instead.' },

      // ── block 7 ──
      { id: 'L1-25', level: 1, cat: 'smells', answer: 'think',
        situation: 'You sit next to a classmate at lunch. Their food smells really strong.',
        utterance: 'That smells gross.', sayVerb: 'say', object: 'these words',
        features: { selfEsteem: 'hurts', relationship: 'classmate' },
        vary: { setting: 'school', person: 'peer', topic: 'smell', form: 'statement' },
        reason: 'Think it. These words would hurt their feelings about their food.' },
      { id: 'L1-26', level: 1, cat: 'kind', answer: 'say',
        situation: 'Your mom makes your favorite dinner.',
        utterance: 'This tastes SO good!', sayVerb: 'say', object: 'these words',
        features: { selfEsteem: 'lifts', relationship: 'grown-up' },
        vary: { setting: 'home', person: 'family', topic: 'work', form: 'exclamation' },
        reason: 'Say it! It will make Mom happy to hear it.' },
      { id: 'L1-28', level: 1, cat: 'kind', answer: 'say',
        situation: 'Your friend makes it to the top of the climbing wall.',
        utterance: 'You did it!', sayVerb: 'say', object: 'these words',
        features: { selfEsteem: 'lifts', audience: 'others-hear' },
        vary: { setting: 'playground', person: 'peer', topic: 'work', form: 'exclamation' },
        reason: 'Say it! Cheering a friend on is kind and fun.' },
      { id: 'L1-27', level: 1, cat: 'looks', answer: 'think',
        situation: 'A boy in your class has a lot of spots on his face.',
        utterance: 'You have spots all over.', sayVerb: 'say', object: 'these words',
        features: { selfEsteem: 'hurts', changeability: 'not-fixable' },
        vary: { setting: 'school', person: 'peer', topic: 'looks', form: 'statement' },
        reason: 'Think it. He cannot change it, and saying it would embarrass him.' },

      // ── block 8 ──
      { id: 'L1-29', level: 1, cat: 'looks', answer: 'think',
        situation: 'A classmate is wearing two socks that do not match.',
        utterance: 'Your socks do not match.', sayVerb: 'say', object: 'these words',
        features: { selfEsteem: 'hurts', changeability: 'not-fixable' },
        vary: { setting: 'school', person: 'peer', topic: 'looks', form: 'statement' },
        reason: 'Think it. They cannot change their socks at school, so saying it would just embarrass them.' },
      { id: 'L1-30', level: 1, cat: 'kind', answer: 'say',
        situation: 'Your teacher reads a really funny story and you laugh.',
        utterance: 'That story was so funny!', sayVerb: 'say', object: 'these words',
        features: { selfEsteem: 'lifts', relationship: 'grown-up' },
        vary: { setting: 'school', person: 'teacher', topic: 'work', form: 'exclamation' },
        reason: 'Say it! Your teacher will feel happy you liked it.' },
      { id: 'L1-31', level: 1, cat: 'kind', answer: 'say',
        situation: 'Your friend helps you pick up your crayons when you drop them.',
        utterance: 'Thank you, that was really nice!', sayVerb: 'say', object: 'these words',
        features: { selfEsteem: 'lifts', relationship: 'close-friend' },
        vary: { setting: 'school', person: 'peer', topic: 'belongings', form: 'exclamation' },
        reason: 'Say it! Saying thank you is kind and makes friends feel good.' },
      { id: 'L1-35', level: 1, cat: 'private', answer: 'think',
        situation: 'A classmate has a bandage on their arm and you are curious about it. Lots of kids are standing around you both.',
        utterance: 'How did you get that?', sayVerb: 'ask', object: 'this question',
        features: { privacy: 'private', audience: 'others-hear' },
        vary: { setting: 'school', person: 'peer', topic: 'body', form: 'question' },
        reason: 'Think it for now. Asking in front of everyone could embarrass them.' },

      // ── tail ──
      { id: 'L1-32', level: 1, cat: 'kind', answer: 'say',
        situation: 'It is your friend’s birthday and they are wearing a big birthday badge.',
        utterance: 'Happy birthday!', sayVerb: 'say', object: 'these words',
        features: { selfEsteem: 'lifts', timing: 'right-moment' },
        vary: { setting: 'school', person: 'peer', topic: 'belongings', form: 'exclamation' },
        reason: 'Say it! Wishing a friend happy birthday makes them feel special.' },
      { id: 'L1-33', level: 1, cat: 'kind', answer: 'say',
        situation: 'A classmate is sitting alone on the playground and looks sad.',
        utterance: 'Are you okay?', sayVerb: 'ask', object: 'this question',
        features: { override: 'help-or-safety', relationship: 'classmate' },
        vary: { setting: 'playground', person: 'peer', topic: 'body', form: 'question' },
        reason: 'Say it! Asking kindly helps them feel less alone.' },
      { id: 'L1-34', level: 1, cat: 'kind', answer: 'say',
        situation: 'You finished all of your work and you feel proud of it.',
        utterance: 'I did it!', sayVerb: 'tell', object: 'this news',
        features: { selfEsteem: 'lifts', timing: 'right-moment' },
        vary: { setting: 'school', person: 'teacher', topic: 'work', form: 'exclamation' },
        reason: 'Say it! Sharing happy news about yourself is great.' },
    ],
    // One matched minimum-difference pair per criterial dimension. `defeater` is
    // dimension 8: truth is held CONSTANT across both cards and something else
    // flips, which is the demonstration that truth is not what decides.
    pairs: [
      { dim: 'selfEsteem',    a: 'L1-01', b: 'L1-02' },
      { dim: 'privacy',       a: 'L1-03', b: 'L1-04' },
      { dim: 'changeability', a: 'L1-05', b: 'L1-06' },
      { dim: 'audience',      a: 'L1-07', b: 'L1-08' },
      { dim: 'relationship',  a: 'L1-09', b: 'L1-10' },
      { dim: 'timing',        a: 'L1-11', b: 'L1-12' },
      { dim: 'override',      a: 'L1-13', b: 'L1-14' },
      { dim: 'truthNotTest',  a: 'L1-15', b: 'L1-16', kind: 'defeater' },
    ],
  };
})(typeof window !== 'undefined' ? window : globalThis);
