/* ── Think or Say? — Level 2 "Nuanced" ─────────────────────────────────
   The answer depends on a feature of the SITUATION, not on the words alone:
   true-but-hurtful observations, private things noticed, comments where
   audience / timing / volume decides, and curious questions that would
   embarrass the person asked.

   Where the same words flip on context, the card text CARRIES that context. A
   card whose answer depends on information the learner was never given is a
   broken card, not a hard one — so "you are right beside them, nobody else can
   hear" and "you are across the lunchroom" are written into the situation.

   Content rule and ORDER IS DATA: see cards-level-1.js. This pool runs
   THINK, THINK, SAY, SAY in blocks of four, then a THINK tail.
   ----------------------------------------------------------------------- */
(function (global) {
  'use strict';

  global.ThinkOrSayLevel2 = {
    id: 2,
    name: 'Nuanced',
    blurb: 'The situation decides — audience, timing, privacy, what can be changed.',
    cards: [
      // ── block 1 ──
      { id: 'L2-01', level: 2, cat: 'work', answer: 'think',
        situation: 'Your friend practised a song for weeks. At the concert they sang some notes wrong, and you heard it.',
        utterance: 'You sang some notes wrong.', sayVerb: 'say', object: 'these words',
        features: { selfEsteem: 'hurts', truthNotTest: 'true' },
        vary: { setting: 'school', person: 'peer', topic: 'work', form: 'statement' },
        reason: 'Think it. It is true, and it would take away all the good they feel about the concert.' },
      { id: 'L2-03', level: 2, cat: 'private', answer: 'think',
        situation: 'Your close friend is beside you. They look embarrassed and are holding a hand over a spot on their skirt. You have noticed the spot too.',
        utterance: 'There is a spot on your skirt.', sayVerb: 'say', object: 'these words',
        features: { privacy: 'private', relationship: 'close-friend' },
        vary: { setting: 'school', person: 'peer', topic: 'belongings', form: 'statement' },
        reason: 'Think it. They already know, and they are trying to keep it private. Saying it would make them feel worse.' },
      { id: 'L2-02', level: 2, cat: 'kind', answer: 'say',
        situation: 'Your friend practised a song for weeks. At the concert they remembered every single word, and you heard it.',
        utterance: 'You remembered every word.', sayVerb: 'say', object: 'these words',
        features: { selfEsteem: 'lifts', truthNotTest: 'true' },
        vary: { setting: 'school', person: 'peer', topic: 'work', form: 'statement' },
        reason: 'Say it! It is true and it is kind — telling them what went well helps them want to try again.' },
      { id: 'L2-04', level: 2, cat: 'other', answer: 'say',
        situation: 'Your close friend is beside you. A sticker has come loose on their bag and is about to fall off. They have not noticed.',
        utterance: 'There is a sticker falling off your bag.', sayVerb: 'say', object: 'these words',
        features: { privacy: 'not-private', relationship: 'close-friend' },
        vary: { setting: 'school', person: 'peer', topic: 'belongings', form: 'statement' },
        reason: 'Say it. Nothing here is private, and telling them saves the sticker.' },

      // ── block 2 ──
      { id: 'L2-06', level: 2, cat: 'looks', answer: 'think',
        situation: 'You are sitting right beside your friend at lunch. Nobody else can hear you. They got a new haircut yesterday and it looks strange to you.',
        utterance: 'Your haircut looks strange.', sayVerb: 'say', object: 'these words',
        features: { changeability: 'not-fixable', audience: 'just-them' },
        vary: { setting: 'school', person: 'peer', topic: 'looks', form: 'statement' },
        reason: 'Think it. Even said quietly, they cannot change their hair today — so it would only hurt.' },
      { id: 'L2-07', level: 2, cat: 'other', answer: 'think',
        situation: 'You are all the way across the lunchroom from your friend, with a lot of people in between. They have a bit of spinach stuck in their teeth.',
        utterance: 'You have something in your teeth!', sayVerb: 'say', object: 'these words',
        features: { audience: 'others-hear', changeability: 'fixable-now' },
        vary: { setting: 'school', person: 'peer', topic: 'body', form: 'exclamation' },
        reason: 'Think it. They could fix it — but calling it across the room means everyone hears, and that embarrasses them.' },
      { id: 'L2-05', level: 2, cat: 'kind', answer: 'say',
        situation: 'You are sitting right beside your friend at lunch. Nobody else can hear you. They have a bit of spinach stuck in their teeth.',
        utterance: 'You have something in your teeth.', sayVerb: 'say', object: 'these words',
        features: { changeability: 'fixable-now', audience: 'just-them' },
        vary: { setting: 'school', person: 'peer', topic: 'body', form: 'statement' },
        reason: 'Say it — quietly, just to them. They can fix it right now, and nobody else hears.' },
      { id: 'L2-09', level: 2, cat: 'kind', answer: 'say',
        situation: 'Your close friend is beside you at lunch. They are holding up a new bandage on their arm to show you.',
        utterance: 'How did you get that?', sayVerb: 'ask', object: 'this question',
        features: { relationship: 'close-friend', privacy: 'private' },
        vary: { setting: 'school', person: 'peer', topic: 'body', form: 'question' },
        reason: 'Say it. They are your close friend and they are showing you, so they want to talk about it.' },

      // ── block 3 ──
      { id: 'L2-08', level: 2, cat: 'private', answer: 'think',
        situation: 'A person you have never met is in the shop line in front of you. You can see a scar on their arm and you are curious.',
        utterance: 'How did you get that?', sayVerb: 'ask', object: 'this question',
        features: { relationship: 'stranger', privacy: 'private' },
        vary: { setting: 'shop', person: 'stranger', topic: 'body', form: 'question' },
        reason: 'Think it. You do not know them, and their body is private. Being curious is fine — asking is not.' },
      { id: 'L2-10', level: 2, cat: 'other', answer: 'think',
        situation: 'Your friend is in the middle of their turn in the class play. You are right beside them and only they could hear you. Their shirt is on inside out.',
        utterance: 'Your shirt is inside out.', sayVerb: 'say', object: 'these words',
        features: { timing: 'wrong-moment', audience: 'just-them' },
        vary: { setting: 'school', person: 'peer', topic: 'belongings', form: 'statement' },
        reason: 'Think it for now. They are in the middle of their turn — this can wait one minute.' },
      { id: 'L2-11', level: 2, cat: 'other', answer: 'say',
        situation: 'Your friend has finished their turn in the class play. You are right beside them and only they can hear you. Their shirt is on inside out.',
        utterance: 'Your shirt is inside out.', sayVerb: 'say', object: 'these words',
        features: { timing: 'right-moment', audience: 'just-them' },
        vary: { setting: 'school', person: 'peer', topic: 'belongings', form: 'statement' },
        reason: 'Say it — quietly, now that they are finished. This is the right moment.' },
      { id: 'L2-12', level: 2, cat: 'other', answer: 'say',
        situation: 'A classmate once told you privately that they get very bad headaches. Right now they have gone pale and cannot stand up.',
        utterance: 'My classmate needs help.', sayVerb: 'tell', object: 'this news',
        features: { override: 'help-or-safety', privacy: 'private' },
        vary: { setting: 'school', person: 'peer', topic: 'body', form: 'statement' },
        reason: 'Say it! It was private — but they need help right now, and help always comes first.' },

      // ── block 4 ──
      { id: 'L2-13', level: 2, cat: 'private', answer: 'think',
        situation: 'A classmate once told you privately that they get very bad headaches. Right now they are fine and playing with everyone else.',
        utterance: 'My classmate gets bad headaches.', sayVerb: 'tell', object: 'this news',
        features: { override: 'none', privacy: 'private' },
        vary: { setting: 'school', person: 'peer', topic: 'body', form: 'statement' },
        reason: 'Think it. Nobody needs help right now, so their private news stays theirs to tell.' },
      { id: 'L2-14', level: 2, cat: 'looks', answer: 'think',
        situation: 'It is true — your classmate is the shortest person in the whole class.',
        utterance: 'You are the shortest in the class.', sayVerb: 'say', object: 'these words',
        features: { truthNotTest: 'true', changeability: 'not-fixable' },
        vary: { setting: 'school', person: 'peer', topic: 'body', form: 'statement' },
        reason: 'Think it. It is true, and there is nothing they can do about it — so it only hurts.' },
      { id: 'L2-15', level: 2, cat: 'other', answer: 'say',
        situation: 'It is true — your classmate has a big smudge of paint on their hand, and the sink is right beside them.',
        utterance: 'You have paint on your hand.', sayVerb: 'say', object: 'these words',
        features: { truthNotTest: 'true', changeability: 'fixable-now' },
        vary: { setting: 'school', person: 'peer', topic: 'body', form: 'statement' },
        reason: 'Say it. It is true AND they can wash it off right now, so telling them helps.' },
      { id: 'L2-18', level: 2, cat: 'other', answer: 'say',
        situation: 'You see a classmate take something out of another kid’s bag when they think nobody is looking.',
        utterance: 'I need to tell you something.', sayVerb: 'tell', object: 'this news',
        features: { override: 'help-or-safety', relationship: 'grown-up' },
        vary: { setting: 'school', person: 'teacher', topic: 'belongings', form: 'statement' },
        reason: 'Say it! When something is not safe or not fair, telling a grown-up is the right thing.' },

      // ── block 5 ──
      { id: 'L2-16', level: 2, cat: 'work', answer: 'think',
        situation: 'Your friend shows you their new backpack. You do not like how it looks.',
        utterance: 'I do not like that backpack.', sayVerb: 'say', object: 'these words',
        features: { selfEsteem: 'hurts', relationship: 'close-friend' },
        vary: { setting: 'school', person: 'peer', topic: 'belongings', form: 'statement' },
        reason: 'Think it. They love their backpack — these words would hurt their feelings.' },
      { id: 'L2-17', level: 2, cat: 'other', answer: 'think',
        situation: 'Your class is in the middle of a quiet test. You have just noticed that your teacher’s tie looks funny to you.',
        utterance: 'Your tie looks funny!', sayVerb: 'say', object: 'these words',
        features: { timing: 'wrong-moment', audience: 'others-hear' },
        vary: { setting: 'school', person: 'teacher', topic: 'belongings', form: 'exclamation' },
        reason: 'Think it. Everyone is working quietly, and calling it out would interrupt the whole class.' },
      { id: 'L2-21', level: 2, cat: 'kind', answer: 'say',
        situation: 'Your teacher got a new haircut and you really like it. You are standing right beside her.',
        utterance: 'I like your haircut!', sayVerb: 'say', object: 'these words',
        features: { selfEsteem: 'lifts', relationship: 'grown-up' },
        vary: { setting: 'school', person: 'teacher', topic: 'looks', form: 'exclamation' },
        reason: 'Say it! A kind compliment is a nice thing to share.' },
      { id: 'L2-28', level: 2, cat: 'other', answer: 'say',
        situation: 'A classmate took your turn by accident. The game has stopped and everyone is waiting.',
        utterance: 'It is my turn now, please.', sayVerb: 'say', object: 'these words',
        features: { timing: 'right-moment', relationship: 'classmate' },
        vary: { setting: 'playground', person: 'peer', topic: 'work', form: 'statement' },
        reason: 'Say it. Speaking up kindly about your turn is fair, and this is the right moment.' },

      // ── tail ──
      { id: 'L2-19', level: 2, cat: 'smells', answer: 'think',
        situation: 'A grown-up bends down to help you and you notice their breath.',
        utterance: 'Your breath smells.', sayVerb: 'say', object: 'these words',
        features: { selfEsteem: 'hurts', relationship: 'grown-up' },
        vary: { setting: 'school', person: 'teacher', topic: 'smell', form: 'statement' },
        reason: 'Think it. Saying it would be embarrassing for them.' },
      { id: 'L2-20', level: 2, cat: 'private', answer: 'think',
        situation: 'A classmate is picking their nose. You are the only one who has seen it.',
        utterance: 'I saw you picking your nose.', sayVerb: 'say', object: 'these words',
        features: { privacy: 'private', audience: 'just-them' },
        vary: { setting: 'school', person: 'peer', topic: 'body', form: 'statement' },
        reason: 'Think it. Even said quietly, it would embarrass them — and nobody else saw.' },
      { id: 'L2-22', level: 2, cat: 'looks', answer: 'think',
        situation: 'Your grandma comes to visit. She has some hair missing on her head.',
        utterance: 'You do not have much hair.', sayVerb: 'say', object: 'these words',
        features: { selfEsteem: 'hurts', relationship: 'grown-up' },
        vary: { setting: 'home', person: 'family', topic: 'looks', form: 'statement' },
        reason: 'Think it. Saying it might make Grandma feel sad.' },
      { id: 'L2-23', level: 2, cat: 'looks', answer: 'think',
        situation: 'You see a kid at school. They have a really big tummy.',
        utterance: 'You have a big tummy.', sayVerb: 'say', object: 'these words',
        features: { selfEsteem: 'hurts', changeability: 'not-fixable' },
        vary: { setting: 'school', person: 'peer', topic: 'looks', form: 'statement' },
        reason: 'Think it. Talking about how someone’s body looks can hurt their feelings.' },
      { id: 'L2-24', level: 2, cat: 'looks', answer: 'think',
        situation: 'Your teacher is wearing pants that look really silly to you.',
        utterance: 'Those pants look funny.', sayVerb: 'say', object: 'these words',
        features: { selfEsteem: 'hurts', relationship: 'grown-up' },
        vary: { setting: 'school', person: 'teacher', topic: 'belongings', form: 'statement' },
        reason: 'Think it. It would make your teacher feel bad.' },
      { id: 'L2-25', level: 2, cat: 'looks', answer: 'think',
        situation: 'A man you have never met is on the bus, and he is very, very tall.',
        utterance: 'You are so tall!', sayVerb: 'say', object: 'these words',
        features: { selfEsteem: 'hurts', relationship: 'stranger' },
        vary: { setting: 'bus', person: 'stranger', topic: 'looks', form: 'exclamation' },
        reason: 'Think it. Pointing out how someone’s body looks can embarrass them, especially someone you do not know.' },
      { id: 'L2-26', level: 2, cat: 'private', answer: 'think',
        situation: 'A classmate pulls up their pants in the line and you see their underwear. Other kids are all around.',
        utterance: 'I saw your underwear.', sayVerb: 'say', object: 'these words',
        features: { privacy: 'private', audience: 'others-hear' },
        vary: { setting: 'school', person: 'peer', topic: 'body', form: 'statement' },
        reason: 'Think it. That is private — saying it with everyone around would embarrass them.' },
      { id: 'L2-27', level: 2, cat: 'other', answer: 'think',
        situation: 'A baby on the bus is crying very loudly, and the baby’s family is right there.',
        utterance: 'That baby is so loud!', sayVerb: 'say', object: 'these words',
        features: { selfEsteem: 'hurts', audience: 'others-hear' },
        vary: { setting: 'bus', person: 'family', topic: 'body', form: 'exclamation' },
        reason: 'Think it. The baby’s family can hear you, and saying it would make them feel bad.' },
    ],
    pairs: [
      { dim: 'selfEsteem',    a: 'L2-01', b: 'L2-02' },
      { dim: 'privacy',       a: 'L2-03', b: 'L2-04' },
      { dim: 'changeability', a: 'L2-05', b: 'L2-06' },
      // The maintainer's worked example: same words, same fixable problem, and
      // only who can hear is different.
      { dim: 'audience',      a: 'L2-05', b: 'L2-07' },
      { dim: 'relationship',  a: 'L2-08', b: 'L2-09' },
      { dim: 'timing',        a: 'L2-10', b: 'L2-11' },
      { dim: 'override',      a: 'L2-12', b: 'L2-13' },
      { dim: 'truthNotTest',  a: 'L2-14', b: 'L2-15', kind: 'defeater' },
    ],
  };
})(typeof window !== 'undefined' ? window : globalThis);
