/* More passages, written for his weak keys.
 *
 * His drills of 2026-09 miss most on w, m, b, u and c, so these passages lean
 * on words that use them (behavior, must, much, which, would, when,
 * communication, cumulative, burst, BCBA) while staying ordinary clinical
 * prose. A test checks that the set carries more of those letters than the
 * first sixteen do.
 *
 * Same rules as passages.js: a study is a plain summary written for the drill,
 * never an abstract; a take is the drill's own position and says so; ASCII
 * only. Every source names a work the drill is certain exists, the textbook
 * by chapter, the Ethics Code, or general practice knowledge. A test lists the
 * allowed works by name, so a new citation is added on purpose or not at all.
 */

export const PASSAGES_MORE = Object.freeze([
  { id: "p-hanley03", outline: "F.6", kind: "study", title: "Functional analysis of problem behavior: a review",
    source: "Hanley, Iwata & McCord (2003), JABA",
    text: "Hanley, Iwata and McCord gathered the functional analyses that had been published up to their time and asked what the body of work showed as a whole. Self-injury was the behavior most often studied, with aggression and disruption behind it, and most of the people served had intellectual disabilities. When a clear function was found, escape from demands and access to attention were the ones that came up most, with automatic reinforcement and access to tangible items less common, and a number of cases showed more than one function at once. The review also tracked how the method had changed. Many teams had begun to use briefer analyses, to add conditions such as a tangible test, and to adapt the conditions to the person rather than copy the original four. Their summary was cautious but clear: the functional analysis had become a common method across many behaviors and settings, and much of its value came from the way it could be modified without losing its experimental logic.",
    respond: "Which modification of the standard analysis do you use most, and what would you lose by using it on every client?" },

  { id: "p-hanley14", outline: "F.6", kind: "study", title: "Producing meaningful improvements in problem behavior via synthesized analyses and treatments",
    source: "Hanley, Jin, Vanselow & Hanratty (2014), JABA",
    text: "Hanley and his colleagues worked with three children with autism whose problem behavior was serious enough to need treatment. Rather than test each consequence alone, the team began with an open-ended interview with caregivers and a brief observation, then built a single test condition that combined the events caregivers had described, such as removing a favored activity, asking the child to stop, and withholding attention, and returned all of them together when problem behavior occurred. A matched control condition gave the child those same things freely. Problem behavior was higher in the test condition for each child, which the authors took as evidence of a synthesized function. Treatment then taught a simple communication response, then a more complex one, then a way to tolerate a delay or a denial, and finally to keep cooperating with demands. Problem behavior fell to low levels as the demands and delays grew. The study is now at the center of a debate about whether combining contingencies is a strength or a blur.",
    respond: "Would you run a synthesized analysis on your next referral? Make the best case against doing it." },

  { id: "p-vollmer", outline: "G.3", kind: "study", title: "The role of attention in the treatment of attention-maintained self-injury: NCR and DRO",
    source: "Vollmer, Iwata, Zarcone, Smith & Mazaleski (1993), JABA",
    text: "Vollmer and his colleagues worked with three adults whose self-injury was maintained by attention, as shown by a functional analysis. They compared two treatments. In one, called noncontingent reinforcement, attention was delivered on a time-based schedule regardless of behavior, starting very dense and then thinned. In the other, differential reinforcement of other behavior, attention came only after a set interval passed with no self-injury. Both treatments reduced self-injury to low levels. The authors pointed out that noncontingent reinforcement gave the person more attention overall and did not depend on the person going without the behavior, which may matter when a burst of self-injury would be dangerous. Much of the later work on time-based schedules built on this comparison. The common misreading is that noncontingent means random or careless; in practice the schedule is planned, measured and thinned as carefully as any other procedure, and it works best when the function is known.",
    respond: "A BT says NCR is just rewarding bad behavior for free. How would you answer, and where would you agree?" },

  { id: "p-horner", outline: "H.3", kind: "study", title: "The effects of response efficiency on functional equivalence training",
    source: "Horner & Day (1991), JABA",
    text: "Horner and Day showed that a replacement behavior can match the function of problem behavior and still lose to it. They worked with individuals whose aggression or self-injury was maintained by escape, and taught each of them a communication response that produced the same break. Then they varied how efficient the new response was, on three dimensions. When the communication response took much more physical effort than the problem behavior, such as signing a full sentence instead of a single sign, problem behavior continued. When the new response had to be emitted several times to earn one break while the problem behavior earned it every time, problem behavior continued. When the new response produced the break only after a delay, problem behavior continued. When the communication response was at least as efficient on each dimension, problem behavior dropped. The lesson for treatment plans is blunt: a mand must be easier, quicker and more reliably paid off than the behavior it is meant to replace.",
    respond: "Look at the last replacement behavior you wrote into a plan. Which of the three dimensions would it lose on?" },

  { id: "p-lovaas", outline: "D.5", kind: "study", title: "Behavioral treatment and normal educational and intellectual functioning in young autistic children",
    source: "Lovaas (1987), Journal of Consulting and Clinical Psychology",
    text: "Lovaas reported on young children with autism who received about forty hours a week of one-to-one behavioral treatment for two or more years, and compared them with children who received about ten hours a week or who were served elsewhere. Nine of the nineteen children in the intensive group, or 47 percent, were described as reaching normal intellectual and educational functioning, meaning that they passed first grade in a regular classroom and scored in the average range on IQ tests, compared with about 2 percent of the comparison children. The study became the most cited argument for intensive early intervention. It is also one of the most criticized. Children were not randomly assigned to groups, the outcome measures were broad, and the treatment included contingent aversives, such as a loud no or a slap on the thigh, which almost no current program would use. Much of the later research asked which part of the result would survive better methods and a very different treatment.",
    respond: "A parent quotes the 47 percent to you. What do you tell them the study can and cannot promise?" },

  { id: "p-fisher92", outline: "F.4", kind: "study", title: "A comparison of two approaches for identifying reinforcers for persons with severe and profound disabilities",
    source: "Fisher, Piazza, Bowman, Hagopian, Owens & Slevin (1992), JABA",
    text: "Fisher and his colleagues compared two ways of finding reinforcers for people with severe and profound disabilities. In a single-stimulus approach, each item is presented alone and the analyst records whether the person approaches it. In a paired-choice approach, items are presented two at a time, every item is paired with every other, and the person picks one of each pair. Because a person can approach almost everything when it is offered by itself, the single-stimulus approach tended to rate many items as preferred, which made it hard to tell them apart. The paired approach produced a clearer ranking. The team then checked which items worked as reinforcers in a concurrent arrangement, and the items ranked high by the paired approach generally did better. The practical point is that a preference assessment is only as useful as its ability to separate the items at the top, and a person who says yes to everything has not yet told you much.",
    respond: "Your learner approaches every item you show. Which assessment would you run next, and why?" },

  { id: "p-rincover", outline: "B.11", kind: "study", title: "Sensory extinction: a procedure for eliminating self-stimulatory behavior",
    source: "Rincover (1978), Journal of Abnormal Child Psychology",
    text: "Rincover worked with children with developmental disabilities whose repetitive behavior seemed to be maintained by the sensory consequences it produced rather than by anything another person did. Instead of punishing the behavior or blocking it, he removed or masked the sensory result. For example, a carpet on the table took the sound out of spinning a plate on a hard surface. When the sensory consequence was removed, the behavior decreased, and when it was restored, the behavior came back, which is the pattern extinction would predict. The study mattered because it treated automatic reinforcement as a real contingency that could be analyzed and changed, not as a mystery inside the child. It also carried a caution that clinicians still debate: repetitive behavior that is harmless and that the person values may not be a target at all, and removing a source of reinforcement without adding a better one can leave a person with much less to do.",
    respond: "When would you treat a client's stereotypy, and when would you leave it alone? Be specific." },

  { id: "p-michael", outline: "B.17", kind: "study", title: "Distinguishing between discriminative and motivational functions of stimuli",
    source: "Michael (1982), JEAB",
    text: "Michael argued that behavior analysts were using one word for two different jobs. A discriminative stimulus signals that a particular behavior would be reinforced now, because reinforcement has been more available in its presence than in its absence. An establishing operation does something else. It changes how effective a consequence is as a reinforcer, and in the same moment it changes how often behavior that has produced that consequence occurs. Food deprivation is the standard example: it does not signal that food is available, but it makes food more valuable and makes food-seeking more likely. Michael warned that calling both of these a stimulus that controls behavior would blur the analysis and lead to weaker interventions. Later writers widened the idea into the motivating operation, which includes abolishing operations that reduce a reinforcer's value. In practice, the distinction tells a clinician whether to change what signals reinforcement or to change how much the learner wants it.",
    respond: "Your client mands for the iPad only when it is out of reach. Is the missing iPad an SD or an MO? Argue it." },

  { id: "p-cusps", outline: "F.8", kind: "study", title: "Behavioral cusps: a developmental and pragmatic concept",
    source: "Rosales-Ruiz & Baer (1997), JABA",
    text: "Rosales-Ruiz and Baer proposed a way to rank behavior change by what it opens up rather than by how much effort it took. They called a behavior change a cusp when it gives the person access to new environments, new reinforcers, new contingencies and new people, with consequences that reach well beyond the change itself. Crawling is a cusp for an infant, because the whole room becomes reachable. Reading is a cusp for a child, because every book becomes a teacher. A skill can be hard to teach and still not be a cusp, and a small skill can be a cusp because of what it unlocks. The concept is useful when a team has to choose which goals come first. It asks the clinician to look at the learner's world and predict which change would multiply the most future learning, which is a different question from which skill is next on a curriculum list.",
    respond: "Name one goal on a current plan that is a cusp and one that is not. Would you swap their order?" },

  { id: "p-bst", outline: "I.5", kind: "study", title: "Evidence-based staff training: a guide for practitioners",
    source: "Parsons, Rollyson & Reid (2012), Behavior Analysis in Practice",
    text: "Parsons, Rollyson and Reid described a way to train staff that the research had supported across many settings and many skills, usually called behavioral skills training. The trainer first describes the skill and why it matters. The trainer then gives a brief written summary of the steps. The trainer demonstrates the skill. The trainee practices it, usually first in role play and then on the job. The trainer gives feedback, praising the steps done well and correcting the ones missed. The cycle repeats until the trainee meets a mastery criterion. The authors stressed that the steps work as a package and that the performance-based parts, the demonstration, the practice and the feedback, are the ones most often skipped when a supervisor is busy. A lecture and a signed form may meet a requirement, but they rarely produce a staff member who can run the procedure with a real client on a busy afternoon.",
    respond: "Which step of training do you cut first when your week is full, and what does that cost your BTs?" },

  { id: "p-cdc", outline: "C.11", kind: "study", title: "Visual aids and structured criteria for improving visual inspection and interpretation of single-case designs",
    source: "Fisher, Kelley & Lomas (2003), JABA",
    text: "Fisher, Kelley and Lomas started from a known problem: people who inspect the same single-case graph often disagree about whether an effect occurred, and they can see effects in data where none exists. The authors proposed a structured method. A mean line and a trend line are calculated from the baseline and projected into the treatment phase, and the analyst counts how many treatment points fall above or below both lines, then compares that count with a number set by a simple probability rule. In the conservative version, both lines are shifted by a quarter of a standard deviation, which makes a false positive less likely. The method produced fewer errors than unaided judgment, especially with data that carried a trend, and staff who were trained on it inspected graphs more accurately. The method does not replace clinical judgment, but it gives a clinician a written rule to check a hunch against before a program is changed.",
    respond: "Would you require a structured rule before a BT's program is changed on your caseload? Why or why not?" },

  { id: "p-lalli", outline: "G.1", kind: "study", title: "Competition between positive and negative reinforcement in the treatment of escape behavior",
    source: "Lalli et al. (1999), JABA",
    text: "Lalli and his colleagues worked with participants whose problem behavior was maintained by escape from tasks. The usual treatment would combine a break for compliance with escape extinction, so that problem behavior no longer ended the task. This team asked a different question: what happens if compliance earns something better than a break, such as a preferred edible, even when problem behavior still produces escape. For the participants, positive reinforcement for compliance reduced problem behavior and increased compliance, in some cases without escape extinction at all. The finding matters because escape extinction can be hard to carry out, can be physically demanding, and can produce bursts and aggression. The study suggested that the value of what a learner earns for cooperating can compete with the value of getting out of the work. It does not mean the break is irrelevant, but it widens the menu a clinician can use when extinction is not safe or not acceptable to the family.",
    respond: "A family refuses escape extinction. Build the treatment you would offer them from this study." },

  { id: "p-compassion", outline: "E.8", kind: "take", title: "The drill's take: compassion is a clinical skill, and it can be taught",
    source: "The drill's own position, drawing on Taylor, LeBlanc & Nosik (2019), Behavior Analysis in Practice",
    text: "Here is the position. The relationship between a BCBA and a family is not a soft extra that sits beside the treatment; it is part of the treatment. A caregiver who feels judged, rushed or unheard will carry out less of the plan, will bring less information to the team, and will be more likely to leave services. Taylor, LeBlanc and Nosik made a version of this case and called for behavior analysts to be trained in compassionate care, meaning skills such as listening without interrupting, reflecting what a parent has said, and asking about the family's day before asking for data. Those skills can be defined, modeled, practiced and given feedback, like any other repertoire. A clinician who says they are just not a people person is describing a skill they have not been taught, not a trait they are stuck with. Supervision that measures treatment fidelity but never measures how a caregiver was spoken to is measuring half the job.",
    respond: "How would you measure compassion in a supervisee without turning it into a checklist nobody believes?" },

  { id: "p-mand", outline: "B.19", kind: "take", title: "The drill's take: teach the mand before the tact",
    source: "The drill's own position, drawing on Skinner (1957), Verbal Behavior, and Cooper, Heron & Heward (2020), ch. Verbal Behavior",
    text: "Here is the position. For an early learner with little or no vocal behavior, the first verbal operant to build should usually be the mand. A mand is verbal behavior under the control of a motivating operation and followed by the specific reinforcer it names, so a child who says cookie and gets a cookie has contacted a contingency that works for the child right away. A tact, naming a cookie in a picture because a teacher asked, pays off only with praise or a token, which may mean little to a child who has not yet learned that talking is worth the effort. Manding also gives the child a way to get what problem behavior has been getting. None of this means the tact is unimportant, or that a program should wait for dozens of mands before any tact training begins. It means the order matters, because a child who has learned that words move the world is a child who will work to learn more of them.",
    respond: "Your client has forty tacts and three mands. What went wrong, and what would you change on Monday?" },

  { id: "p-measure", outline: "C.9", kind: "take", title: "The drill's take: choose the measure that matches the behavior",
    source: "The drill's own position, drawing on Cooper, Heron & Heward (2020), ch. Measuring Behavior",
    text: "Here is the position. A measurement system should be chosen for the behavior and the decision it has to support, not for what the last program used. Count the behavior when it has a clear beginning and end and does not happen so fast that counting becomes guessing. Measure duration when the problem is how long a behavior lasts, such as a tantrum, and latency when the problem is how long it takes to begin, such as starting work. Use whole-interval recording only when you are willing to underestimate the behavior, because an interval counts only if the behavior filled it, and partial-interval recording only when you are willing to overestimate it, because a brief occurrence marks the whole interval. Momentary time sampling can work for behavior that lasts, if the intervals are short enough. The worst measure is the one a busy BT cannot carry out, because a data sheet that is filled in at the end of the session from memory measures memory, not behavior.",
    respond: "Pick a behavior on your caseload that is measured the wrong way. What would you switch to, and what would it cost?" },

  { id: "p-caseload", outline: "E.12", kind: "take", title: "The drill's take: a caseload number is a clinical decision",
    source: "The drill's own position, drawing on general practice knowledge and the BACB Ethics Code for Behavior Analysts (2020)",
    text: "Here is the position. The number of clients a BCBA carries is not only a business number; it sets a ceiling on how much supervision, data review and caregiver contact each client can receive. When the caseload climbs, the first things to go are the ones nobody bills for: the careful look at a flat graph, the call to a worried parent, the second observation of a BT who seemed unsure. The client whose program stalls quietly is the one who pays. A clinician should be able to say, for each client, when they last looked at the data and what they changed because of it. If the honest answer for several clients is that nothing changed because nobody looked, the caseload is too large for the clinician, whatever the company average says. The Ethics Code puts the duty to provide effective treatment on the behavior analyst, not on the scheduler, which means the BCBA must be willing to say no to one more.",
    respond: "What is the right caseload for you, and what would you have to believe to accept one more client?" },

  { id: "p-mastery", outline: "H.7", kind: "take", title: "The drill's take: mastery means it works outside the teaching room",
    source: "The drill's own position, drawing on general practice knowledge",
    text: "Here is the position. A target is not mastered because a learner answered correctly on three sessions in a row with one instructor at one table. That shows acquisition under narrow conditions, which is a useful step but not the goal. A skill should be called mastered only when it occurs with more than one person, with more than one set of materials, in the settings where the learner will actually need it, and after some time has passed without teaching. Programs that move targets to mastered too early build a long list of skills that look complete on a report and do not show up at home, at school, or with a new BT. The fix is not a harder criterion on the same table. It is a criterion that includes generalization and maintenance probes from the start, and a willingness to move a target back into teaching when a probe fails, without treating it as a failure of the BT or the learner.",
    respond: "What is your mastery criterion right now, and which of your mastered targets would fail a probe tomorrow?" },

  { id: "p-token", outline: "G.4", kind: "take", title: "The drill's take: a token board is a bridge, not a building",
    source: "The drill's own position, drawing on general practice knowledge",
    text: "Here is the position. A token system is a way to deliver conditioned reinforcement quickly and to bridge the delay between behavior and a backup reinforcer, and it works best when it is built on purpose and taken apart on purpose. Tokens only work if they have been paired with backup reinforcers the learner actually wants, and they stop working when the backups become boring or too easy to get elsewhere. A board that earns the same item every time for months is a sign that nobody is checking. A board should also have a plan for its own end: the number of tokens per exchange grows, the delay to exchange grows, and praise and natural reinforcers carry more of the load, until the board is used only when a new or difficult skill is being taught. When a learner can do nothing without a board, the system has become a crutch, and the team should ask whether the board was ever meant to come down.",
    respond: "Which of your clients has had the same token board the longest? What would it take to thin it?" },

  { id: "p-pairing", outline: "G.4", kind: "take", title: "The drill's take: pairing comes before demands, and comes back after bad weeks",
    source: "The drill's own position, drawing on general practice knowledge",
    text: "Here is the position. A new BT should spend the first sessions becoming a source of good things for the learner before placing demands: playing, delivering preferred items and activities, commenting on what the child is doing, and asking for nothing that might be refused. The point is that the BT becomes a conditioned reinforcer, so that later demands come from a person whose presence already predicts good things. Pairing is often rushed because it looks like play and does not produce data a funder recognizes. It should not be treated as a one-time phase. After a run of difficult sessions, after a long break, or when problem behavior is climbing, returning to heavy pairing is often the quickest way to rebuild cooperation. A BT who is met at the door by a child walking away is receiving data about the relationship, and the answer is usually more pairing and fewer demands for a while, not more demands delivered with more firmness.",
    respond: "How would you tell a funder that a week of mostly pairing was the right clinical call?" },

  { id: "p-culture", outline: "E.9", kind: "take", title: "The drill's take: cultural humility changes the goals, not only the manners",
    source: "The drill's own position, drawing on Fong, Catagnus, Brodhead, Quigley & Field (2016), Behavior Analysis in Practice",
    text: "Here is the position. Cultural humility is not a matter of being polite to families whose customs differ from the clinician's. It changes what the team works on. Eye contact, independent eating, sleeping in one's own bed, and speaking only English at home are all goals that some families want and others would reject, and a clinician who assumes them is choosing the family's values for them. Fong and colleagues argued that behavior analysts should examine their own cultural learning history and ask families about theirs, because a plan built on the clinician's defaults can be effective on a graph and still fail the family. The practical habit is simple to name and hard to keep: before a goal is written, the clinician asks who wants this change, why, and what the family would count as success. When the answer surprises the clinician, the plan should change, and the surprise should be treated as information, not as noncompliance.",
    respond: "Which goal did a family once refuse that you now think they were right to refuse?" },

  { id: "p-multrel", outline: "E.7", kind: "take", title: "The drill's take: a multiple relationship starts small and becomes a problem slowly",
    source: "The drill's own position, drawing on the BACB Ethics Code for Behavior Analysts (2020), 1.11 Multiple Relationships",
    text: "Here is the position. Most multiple relationships in behavior analysis do not begin with a clear violation. They begin with a small kindness: a parent who asks the BT to babysit on Saturday, a supervisee who becomes a friend on social media, a family that brings a meal to thank the team. Each one feels harmless, and some are. The Ethics Code asks behavior analysts to avoid multiple relationships and to address them when they arise, because the risk is not the first favor but what it does to the next hard conversation. A BCBA who babysits for a family will find it harder to tell them the plan is not working. A supervisor who is a friend will find it harder to give critical feedback. The practical rule is to talk about the boundary early and in plain words, before the first favor, so that saying no later is a policy the family already knows, not a rejection they feel.",
    respond: "A family invites your BT to their child's birthday party. What do you tell the BT, and what do you tell the family?" },
]);
