/* Variants: the same idea, new words to type.
 *
 * His ask of 2026-09-23: a passage he shelves comes back later "with the text
 * changed for the transcription part, so I get the same idea but practice
 * typing something new". Each variant below restates its passage's content
 * and nothing more: no new claim, no new citation. The source line and the
 * respond question stay the passage's own.
 *
 * ASCII only, as the passages are, so every character is on the keyboard.
 */

import { VARIANTS_MORE } from "./variants-more.js";

const CORE = {
  "p-iwata": [
    "Nine people with developmental disabilities who hurt themselves took part in the study by Iwata and his team. Instead of interviewing staff about why the self-injury happened, the researchers set up short sessions that repeated across several planned conditions. In the attention condition, an adult ignored the person until self-injury occurred and then offered a brief, mild comment of concern. In the demand condition, the adult presented hard tasks and let the person take a short break from them after self-injury. In the alone condition, the person had no materials and no company. The play condition, with toys, attention and no demands, served as the control. For most people, one condition produced clearly more self-injury than the rest, and that condition pointed to the reinforcer keeping it going: attention, escape, or the sensation itself. The lasting contribution was the method, because it tested the cause by changing the environment instead of inferring it from a story.",
  ],
  "p-carr": [
    "In a classroom study, Carr and Durand started by mapping when each child with developmental disabilities showed problem behavior. Some children acted out when adult attention dropped. Others acted out when the tasks became difficult, and a few did both. Each child was then taught a short phrase that requested whatever the problem behavior seemed to produce, for example asking the teacher whether the work was good, or saying that the task was confusing and asking for help. When the taught phrase matched the function, problem behavior fell. When a child learned a phrase that was just as polite but did not match the function, problem behavior stayed. The takeaway most clinicians remember is that a replacement response must do the job the problem behavior had been doing. Nobody trades a behavior that pays off for one that does not.",
  ],
  "p-bwr": [
    "Baer, Wolf and Risley described the features that make work count as applied behavior analysis. It must be applied, focused on behavior that matters to the person and to the people in their life. It must be behavioral, measuring what the person does instead of what they report. It must be analytic, with a convincing demonstration that the intervention, and not some other event, caused the change. It must be technological, written clearly enough that another trained person could replicate it. It must be conceptually systematic, linked to basic principles rather than assembled from tricks. It must be effective, producing change big enough to matter in daily life. It must show generality, so the change lasts, carries into new settings, or spreads to related behavior. More than fifty years later, many clinicians still use these seven dimensions to judge whether a program is truly behavior analytic.",
  ],
  "p-stokes": [
    "When Stokes and Baer reviewed the studies of their day, they found that most researchers hoped generalization would happen but did not plan for it. They named that habit train and hope: teach the skill in one setting, then check afterwards whether it appeared elsewhere. They sorted the tactics that seemed to work. One was to connect the skill with natural reinforcers that would maintain it. Another was to teach with enough examples that the learner responded to the whole class of situations, not a single case. Another was to train loosely, changing the teacher, the wording and the location on purpose. Another was to build common stimuli into both the teaching setting and the everyday one. Another was to make it hard for the learner to tell when reinforcement was coming, so responding continued when it was absent. Their main claim was that generalization is a behavior change to be programmed, never assumed.",
  ],
  "p-wolf": [
    "According to Wolf, a behavior analyst cannot be the only judge of whether a program was worthwhile. Numbers can show that behavior changed, but the people affected are the ones who can say whether the change was important. He suggested checking social validity at three levels. First, whether the goals are the ones the family, the client and the community actually want. Second, whether the procedures are acceptable to the people who carry them out and the people who receive them. Third, whether the results satisfy the consumers, including any side effects nobody planned. He described these measures as subjective by design, using ratings, interviews and opinions. He granted that they are less trustworthy than a count of behavior, but warned that a field ignoring them could produce changes that look real on a graph and mean nothing in a life. The paper is widely cited as the point where the client's own view earned a place in the work.",
  ],
  "p-deleon": [
    "DeLeon and Iwata compared methods for learning what a person prefers. The paired-stimulus method offers two items at a time until every possible pair has been shown. A multiple-stimulus method puts the whole array out at once and lets the person choose one. They examined a version in which a chosen item is removed from the array, so each later choice comes from the items that remain, and the order of choices becomes a ranking. This without-replacement method ranked items much as the paired method did, took less time, and was less likely than the with-replacement method to overlook items the person would still pick once the top item was gone. A preference ranking does not prove that an item will function as a reinforcer. Still, a fast and repeatable ranking made it realistic to check preferences often, which matters because what a person prefers can change from one day to the next.",
  ],
  "p-lerman": [
    "Lerman and Iwata reviewed published cases in which extinction was used for problem behavior, asking how often an extinction burst really occurred, meaning a clear jump in the behavior soon after extinction began. They found bursts in a minority of cases, not in most. Bursts were also rarer when extinction was paired with another procedure, such as reinforcing an alternative behavior or giving the reinforcer on a time-based schedule, than when extinction was used by itself. The clinical reading is that a burst is a genuine risk to plan around, above all with dangerous behavior, but it is not a certainty, and how the treatment is packaged shifts the odds. A clinician who promises a family that it will definitely get worse first is overstating the evidence, and a clinician who promises it will not is understating it.",
  ],
  "p-tiger": [
    "Tiger, Hanley and Bruzek summarized the research on teaching a communication response to replace problem behavior. It starts with identifying the function, because the new response must earn the same reinforcer. The response should be easy for the learner to make and easy for others to see and understand. At first it should be honored every time and right away, while the problem behavior stops producing that reinforcer. The difficult phase comes next. A learner who finds that asking always works may ask all the time, and no parent or teacher can hand out attention or breaks on demand indefinitely. So much of the guide is about thinning the schedule: building in delays, teaching the learner to accept a no or a wait, and using clear signals that show when the reinforcer is available and when it is not. A treatment that ends at the first success often breaks down in daily life.",
  ],
  "p-hart": [
    "In a preschool, Hart and Risley changed the moment when teachers taught language. Rather than holding separate lessons, the teachers waited for a child to begin an exchange, most often by asking for a toy or for help, and taught right then. Before handing over the item, the teacher prompted a slightly fuller request, then gave the item at once. Because the child had picked the item and started the exchange, the motivation was already in place, and the reinforcer was the thing the child wanted rather than praise for finishing a lesson. Across the day, the children came to use more elaborate language. The method became known as incidental teaching. It is an early case of teaching inside ordinary routines and following the child's lead, ideas that later naturalistic approaches developed further.",
  ],
  "p-assent": [
    "The position is this. When a learner makes it clear that they want to stop, by pushing the work away, walking off, crying, or saying no, the adult's next move should change, not just the data sheet. Pushing on anyway can teach the learner that their signals are ignored, and it can make the teaching area a place worth escaping. That is not the same as ending every demand at the first protest. Some protest is escape-maintained behavior that a sound plan is designed to treat, and some demands, like staying out of the road, are not negotiable. What separates a good plan from a poor one is whether these moments were thought through in advance or simply pushed through. The plan should describe what assent looks like for this learner, what withdrawal looks like, and what the adult will do: pause, give a choice, make the task easier, or stop. If the staff cannot say, the plan is incomplete.",
  ],
  "p-graph": [
    "The position is this. Data nobody graphs and nobody reads is paperwork, not data. Each minute a technician spends on tally marks is a minute taken from teaching, so a measure has to earn its place by changing some decision. When a program sits on the same step for a month without anyone noticing, the learner is not the problem, the review is. More data sheets will not fix it. Fewer measures will, graphed on a set schedule, with a rule written ahead of time for what the graph must show before anything changes. Three sessions with no progress, change the prompt. Five sessions at criterion, move to the next step. A supervisor who looks at graphs every week finds a stalled program within days, and one who looks only at reauthorization finds it months later. Collect only what you will use, check it often, and let the graph say when to act.",
  ],
  "p-punish": [
    "The position is this. A punishment procedure should never lead a plan and should never be used alone. Before anyone considers it, the team should know the function of the behavior, should have taught a replacement that meets the same need, and should have made reinforcement for that replacement richer than reinforcement for the problem behavior. Often that is enough, and punishment never comes up. If it does come up, the reasons should be written down, the least restrictive option should be tried first, and the data should show quickly whether it works, because a punisher that is not reducing the behavior is harm without benefit. Punishment can also bring side effects, such as aggression, avoidance of the person delivering it, or a learner who only learns what not to do. A plan that puts punishment first has usually skipped the assessment.",
  ],
  "p-prompt": [
    "The position is this. A learner who waits for a prompt before answering is often called prompt dependent, as though it were a trait of the learner. Usually it is a history of teaching. If the prompt always arrives, and a prompted answer earns the same reinforcer as an independent one, then waiting is the smart move, and the learner has learned just what was taught. The fix belongs to the procedure. Plan the fading before the first session, with a time delay or a least-to-most sequence that really moves forward. Reinforce independent answers more richly than prompted ones. Notice staff who prompt sooner than the plan allows because the session is running behind. When fading stalls, examine the adult before the child. A learner who is still fully prompted after several weeks is telling you something about the plan.",
  ],
  "p-herrnstein": [
    "In Herrnstein's experiment, pigeons could peck either of two keys, and each key delivered food on its own variable-interval schedule. He varied how much reinforcement each key could deliver and measured how the birds divided their pecks. The birds did not choose the richer key and stay with it. Instead, the proportion of pecks on each key came to match the proportion of reinforcement that key delivered. When one key paid about twice as much, it received about twice as many pecks. The finding became known as the matching law, and it reshaped how behavior analysts think about choice. Behavior is always divided among competing sources of reinforcement, never emitted in isolation. In a clinic, a problem behavior on a much richer schedule than its replacement will win that competition, which is why a new behavior must be reinforced faster, more often, or with bigger value than the old one.",
  ],
  "p-mace": [
    "Mace and his colleagues took the idea of momentum from physics and tested whether it could increase compliance. Just before giving a request a person usually refused, staff gave a quick run of short requests the person nearly always followed, praised each one, and then gave the hard request at once. The procedure came to be called the high-probability request sequence. Compliance with the hard request rose compared with giving that request alone. Timing counted: the effect was strongest when the hard request came quickly after the easy ones, and a long pause between them weakened it. The lesson is easy to apply and easy to misapply. The easy requests must really be easy for this person, the praise must be genuine, and the sequence works best as part of a routine rich in reinforcement, not as a trick to get past a single task.",
  ],
  "p-multiple": [
    "The multiple baseline design exists for behavior that cannot be taken back. Once a child has learned to wash hands or to buckle a seat belt, the skill usually stays after teaching ends, so a reversal design would fail and would not be wanted anyway. The analyst instead records two or more baselines at the same time, across behaviors, settings, or people, and starts the intervention on one baseline at a time. If each baseline changes only when the intervention reaches it, and not earlier, the pattern builds a convincing case that the intervention produced the change, and not time passing, maturation, or something new at home. The design is weaker when the baselines depend on each other, since a skill taught in one setting can spread to the next before its turn. It is also slow, because the final baseline waits longest, a cost worth weighing when the behavior matters to the client today.",
  ],
};

export const VARIANTS = Object.freeze({ ...CORE, ...VARIANTS_MORE });

/** The texts a passage can be typed as: the original first, then its variants. */
export function textsFor(passage) {
  if (!passage) return [];
  return [passage.text, ...(VARIANTS[passage.id] || [])];
}
