/* Variants for the passages in passages-more.js: the same idea in new words.
 *
 * Same rule as variants.js: each one restates its passage and nothing more,
 * no new claim and no new citation, so a shelved passage comes back with new
 * typing and the same thing to respond to. ASCII only.
 */

export const VARIANTS_MORE = Object.freeze({
  "p-hanley03": [
    "Hanley, Iwata and McCord brought together the published functional analyses available when they wrote and looked at what the whole collection could tell the field. The behavior studied most often was self-injury, followed by aggression and disruption, and most of the people in the studies had intellectual disabilities. Among cases with a clear result, the functions found most often were escape from demands and access to attention, while automatic reinforcement and access to tangible items came up less, and some cases showed multiple functions. The authors also followed how the method itself had been changing. Brief versions had become more common, teams had added conditions such as a test for tangibles, and many had tailored the conditions to the individual instead of copying the first four. They concluded, with some caution, that the functional analysis was now a widely used method across behaviors and settings, and that much of its usefulness came from how well it could be adapted while keeping its experimental logic.",
  ],
  "p-hanley14": [
    "Working with three children with autism whose problem behavior needed treatment, Hanley and his team did not test one consequence at a time. They started with an open-ended caregiver interview and a short observation, then combined the events caregivers had reported, such as taking away a favorite activity, telling the child to stop, and holding back attention, into one test condition, and restored all of them at once whenever problem behavior happened. In a matched control, the child had all of those things freely. Each child showed more problem behavior in the test condition, which the authors read as evidence of a synthesized function. Treatment came next. The children learned a simple communication response, then a more complex one, then how to accept a delay or a no, and finally how to keep working when asked. Problem behavior dropped to low levels even as the demands and the delays increased. The study now sits at the middle of an argument about whether combining contingencies sharpens the analysis or muddies it.",
  ],
  "p-vollmer": [
    "Three adults took part, each with self-injury that a functional analysis had shown to be maintained by attention. Vollmer and his colleagues compared two treatments. Noncontingent reinforcement delivered attention on a time-based schedule no matter what the person was doing, beginning with a very rich schedule that was gradually thinned. Differential reinforcement of other behavior delivered attention only when a set interval went by without self-injury. Both treatments brought self-injury down to low levels. The authors noted that the time-based schedule gave each person more attention in total and did not require the person to go without the behavior first, which can matter when a burst would put someone at risk. A good deal of later research on time-based schedules grew out of this comparison. People sometimes assume noncontingent means random or careless, but in practice the schedule is planned, measured and thinned with the same care as any procedure, and it works best when the function has been identified.",
  ],
  "p-horner": [
    "A replacement behavior can serve the same function as problem behavior and still be outcompeted, and Horner and Day demonstrated how. The individuals they worked with showed aggression or self-injury maintained by escape, and each was taught a communication response that earned the same break. The researchers then changed how efficient that new response was along three dimensions. When the communication response required much more physical effort, such as signing a whole sentence rather than one sign, the problem behavior kept going. When the new response had to be repeated several times for a single break while problem behavior earned a break every time, the problem behavior kept going. When the new response earned the break only after a wait, the problem behavior kept going. Once the communication response was at least as efficient on every dimension, problem behavior decreased. For anyone writing a treatment plan, the message is plain: the mand must be easier, faster and more dependably reinforced than the behavior it is supposed to replace.",
  ],
  "p-lovaas": [
    "In this report, Lovaas described young children with autism who received roughly forty hours a week of one-to-one behavioral treatment for at least two years, compared with children who received roughly ten hours a week or were treated elsewhere. Of the nineteen children in the intensive group, nine, or 47 percent, were said to have reached normal intellectual and educational functioning, which meant completing first grade in a regular class and scoring in the average IQ range. About 2 percent of the comparison children did so. The report became the argument cited most often for intensive early intervention, and also one of the most criticized studies in the field. Assignment to groups was not random, the outcome measures were broad, and the treatment used contingent aversives, such as a loud no or a slap on the thigh, that current programs would almost never use. Much of the research that followed asked which part of the finding would hold up under stronger methods and a very different treatment.",
  ],
  "p-fisher92": [
    "Two approaches to identifying reinforcers for people with severe and profound disabilities were compared by Fisher and his colleagues. The single-stimulus approach presents one item at a time and records whether the person moves toward it. The paired-choice approach presents two items at once, pairs each item with every other item, and records which one the person takes. Since a person may approach nearly anything that is offered alone, the single-stimulus approach often labeled many items as preferred, and so the items were hard to separate. Paired choice gave a cleaner ranking. The team then tested which items actually functioned as reinforcers in a concurrent arrangement, and those ranked highly by paired choice usually came out ahead. What a clinician can take from this is that a preference assessment is useful only if it separates the items at the top, and a learner who accepts everything has not told the team very much yet.",
  ],
  "p-rincover": [
    "The children in Rincover's study had developmental disabilities and showed repetitive behavior that appeared to be maintained by its sensory consequences, not by anything other people did. Rather than punish or block the behavior, he took away or masked the sensory result it produced. In one example, a carpet placed on the table removed the sound a spinning plate made on a hard surface. With the sensory consequence gone, the behavior decreased, and with the consequence back, the behavior returned, just as extinction predicts. The work was important because it handled automatic reinforcement as a genuine contingency that could be studied and changed, rather than as something mysterious inside the child. It also raised a caution that clinicians still argue about. Repetitive behavior that causes no harm and that the person enjoys may not need to be a target, and taking away a source of reinforcement without offering a better one can leave the person with much less to do.",
  ],
  "p-michael": [
    "According to Michael, behavior analysts had been using a single word for two separate functions. A discriminative stimulus tells the learner that a certain behavior would be reinforced now, because reinforcement has been more available when it is present than when it is absent. An establishing operation works differently. It alters how effective a consequence will be as a reinforcer, and at the same time it alters how often the behavior that has produced that consequence occurs. The usual example is food deprivation, which does not signal that food can be had but does make food more valuable and food-seeking more probable. Michael cautioned that describing both as stimuli that control behavior would muddy the analysis and weaken treatment. Later authors broadened the idea into the motivating operation, which also covers abolishing operations that lower a reinforcer's value. For a clinician, the distinction answers a practical question: change what signals that reinforcement is available, or change how much the learner wants it.",
  ],
  "p-cusps": [
    "Rosales-Ruiz and Baer suggested judging a behavior change by what it makes possible, not by how much work it took to teach. A change counts as a cusp when it brings the person into contact with new environments, reinforcers, contingencies and people, so that its consequences spread far past the change itself. For a baby, crawling is a cusp, since the entire room is suddenly within reach. For a child, reading is a cusp, since every book can now teach. Some skills are difficult to teach and are not cusps at all, while some small skills are cusps because of the doors they open. The idea helps most when a team must decide which goals to work on first. It asks the clinician to study the learner's world and predict which change would multiply future learning the most, which is not the same as asking what comes next on a curriculum checklist.",
  ],
  "p-bst": [
    "The approach Parsons, Rollyson and Reid laid out is usually called behavioral skills training, and research has backed it across many settings and many kinds of skills. First, the trainer explains the skill and why it is important. Next, the trainer hands over a short written summary of the steps. Then the trainer models the skill. After that, the trainee rehearses it, often in role play first and later on the job. The trainer follows with feedback, praising what went well and correcting what was missed. The whole cycle is repeated until the trainee reaches a mastery criterion. The authors emphasized that the steps function as a package, and that the performance-based steps, modeling, rehearsal and feedback, are the ones a busy supervisor is most likely to drop. A lecture followed by a signature may satisfy a requirement, but it seldom produces someone who can carry out the procedure with an actual client on a hectic afternoon.",
  ],
  "p-cdc": [
    "The starting point for Fisher, Kelley and Lomas was a familiar problem. People looking at the same single-case graph often disagree about whether there was an effect, and they sometimes see an effect in data that do not contain one. The authors offered a structured method. From the baseline data, a mean line and a trend line are calculated and extended into the treatment phase, and the analyst counts how many treatment points fall beyond both lines, then checks that count against a number given by a simple probability rule. The conservative version moves both lines by a quarter of a standard deviation, so a false positive becomes less likely. Compared with judgment alone, the method made fewer errors, particularly when the data had a trend, and staff trained to use it read graphs more accurately. It is not a substitute for clinical judgment, but it gives the clinician a written rule to test a hunch against before changing a program.",
  ],
  "p-lalli": [
    "The participants Lalli and his colleagues worked with showed problem behavior that was maintained by escaping tasks. A typical treatment would pair a break for compliance with escape extinction, so problem behavior would stop ending the task. This team asked what would happen if compliance earned something more valuable than a break, such as a preferred edible, while problem behavior continued to produce escape. For these participants, reinforcing compliance with a positive reinforcer lowered problem behavior and raised compliance, sometimes with no escape extinction in place at all. That matters because escape extinction can be difficult to carry out, can demand physical effort from staff, and can lead to bursts and aggression. The results suggested that what a learner earns for cooperating can compete with the value of escaping the work. The break still counts, but the study widens the set of options a clinician can offer when extinction is unsafe or unacceptable to the family.",
  ],
  "p-compassion": [
    "Here is the position. The relationship a BCBA builds with a family is not a pleasant extra sitting next to the treatment. It is part of the treatment. When a caregiver feels judged, hurried or ignored, they carry out less of the plan, share less with the team, and become more likely to drop out of services. Taylor, LeBlanc and Nosik argued along these lines and called for training behavior analysts in compassionate care, which covers skills such as listening without cutting in, reflecting back what a parent said, and asking how the family's day went before asking for data. Each of those skills can be defined, modeled, rehearsed and followed with feedback, the same as any other repertoire. A clinician who claims not to be a people person is describing a skill nobody taught them, not a fixed trait. A supervisor who measures treatment fidelity but never measures how a caregiver was talked to is measuring only half of the work.",
  ],
  "p-mand": [
    "Here is the position. With an early learner who has little or no vocal behavior, the mand should usually be the first verbal operant a program builds. A mand is controlled by a motivating operation and followed by the specific reinforcer it specifies, so when a child says cookie and receives a cookie, the child has met a contingency that pays off immediately. A tact, such as naming a pictured cookie because a teacher asked, is reinforced only by praise or a token, and those may mean little to a child who has not yet learned that talking is worth the work. Manding also hands the child a way to get what problem behavior has been getting. That does not make the tact unimportant, and it does not mean a program must wait for dozens of mands before starting tact training. It means order matters, because a child who has found that words can move the world is a child who will work to learn many more of them.",
  ],
  "p-measure": [
    "Here is the position. A measurement system should fit the behavior and the decision the data must support, not whatever the previous program happened to use. Use a count when the behavior has a clear start and finish and does not occur so quickly that counting turns into guessing. Use duration when the concern is how long a behavior continues, such as a tantrum, and latency when the concern is how long it takes to start, such as beginning work. Use whole-interval recording only if underestimating is acceptable, since an interval is scored only when the behavior filled all of it, and partial-interval recording only if overestimating is acceptable, since one brief occurrence marks the whole interval. Momentary time sampling can suit behavior that lasts, provided the intervals are short. The worst choice is a measure a busy BT cannot actually carry out, because a sheet filled in from memory after the session measures memory, not behavior.",
  ],
  "p-caseload": [
    "Here is the position. How many clients a BCBA carries is not just a business figure, because it caps how much supervision, data review and caregiver contact each client can get. As the caseload grows, the unbilled work goes first: the careful review of a flat graph, the call back to an anxious parent, the second visit to watch a BT who looked unsure. The client whose progress stalls without anyone noticing is the one who bears the cost. For every client, a clinician should be able to name the last time they reviewed the data and what they changed as a result. When the honest answer for several clients is that nothing changed because nobody reviewed anything, the caseload is too big for that clinician, no matter what the company average is. The Ethics Code places the duty of effective treatment on the behavior analyst, not on whoever builds the schedule, so the BCBA must be willing to turn down one more.",
  ],
  "p-mastery": [
    "Here is the position. Three correct sessions in a row with one instructor at one table do not make a target mastered. They show acquisition under narrow conditions, which is a useful step but not the end point. A skill deserves the word mastered only once it shows up with several people, with varied materials, in the places the learner will need it, and after a stretch of time without teaching. Programs that call targets mastered too soon pile up skills that look finished in a report and never appear at home, at school, or with a new BT. The answer is not a stricter criterion at the same table. The answer is a criterion that builds in generalization and maintenance probes from the beginning, along with a willingness to move a target back into teaching when a probe fails, without treating that as a failure by the BT or by the learner.",
  ],
  "p-token": [
    "Here is the position. A token system delivers conditioned reinforcement quickly and bridges the gap between a behavior and a backup reinforcer, and it works best when the team builds it deliberately and removes it deliberately. Tokens work only after they have been paired with backups the learner really wants, and they stop working once the backups grow stale or become easy to get some other way. A board that buys the same item every time for months tells you nobody has been checking. Every board also needs a plan for how it ends: more tokens per exchange, a longer wait before exchange, and more of the load carried by praise and natural reinforcers, until the board appears only when a new or hard skill is being taught. If a learner cannot do anything without a board, the system has turned into a crutch, and the team should ask whether anyone ever planned for it to come down.",
  ],
  "p-pairing": [
    "Here is the position. In the first sessions, a new BT should work on becoming a source of good things for the learner before making demands, which means playing, handing over preferred items and activities, commenting on what the child is doing, and asking for nothing the child might refuse. The goal is for the BT to become a conditioned reinforcer, so that demands later come from someone whose presence already signals good things. Pairing is often hurried because it looks like play and yields no data a funder would recognize. It should not be treated as a phase that happens once. After a string of hard sessions, after a long absence, or when problem behavior is rising, going back to heavy pairing is often the fastest way to rebuild cooperation. When a child walks away as the BT comes through the door, the BT is getting data about the relationship, and the usual answer is more pairing and fewer demands for a while, not firmer demands.",
  ],
  "p-culture": [
    "Here is the position. Cultural humility is more than courtesy toward families whose customs differ from the clinician's own. It changes what the team decides to work on. Eye contact, eating independently, sleeping in one's own bed and speaking only English at home are goals some families want and others would turn down, and a clinician who takes them for granted is choosing the family's values on their behalf. Fong and colleagues argued that behavior analysts should look at their own cultural learning history and ask families about theirs, since a plan resting on the clinician's defaults can succeed on a graph and still fail the family. The habit is easy to describe and hard to maintain: before writing a goal, the clinician asks who wants the change, why they want it, and what the family would call success. When the answer is a surprise, the plan should change, and the surprise should be treated as information rather than as noncompliance.",
  ],
  "p-multrel": [
    "Here is the position. In behavior analysis, most multiple relationships do not start as an obvious violation. They start as a small kindness, such as a parent asking the BT to babysit on a Saturday, a supervisee who becomes a friend online, or a family bringing the team a meal to say thank you. Each one seems harmless, and some of them are. The Ethics Code asks behavior analysts to avoid multiple relationships and to deal with them when they come up, since the danger lies less in the first favor than in what it does to the next difficult conversation. A BCBA who babysits for a family will struggle more to tell them the plan is failing. A supervisor who is also a friend will struggle more to give critical feedback. The practical rule is to discuss the boundary early and plainly, before any favor is asked, so that a later no is a policy the family already knows rather than a rejection they take personally.",
  ],
});
